Adding suggestion if pg installation fails

diff --git a/bin/setup_new b/bin/setup_new
--- a/bin/setup_new
+++ b/bin/setup_new
@@ -111,6 +111,7 @@ has_bundler (){
 verify_bundled_gems () {
   has_bundler || install_bundler
   bundle_check || bundle_install || {
+    check_pg || pg_message
     echo 'Unable to install all dependencies from Gemfile. Make sure `bundle install` succeeds before continuing.'
     exit 1
   }
@@ -129,6 +130,18 @@ bundle_install () {
   bundle install
 }
 
+check_pg () {
+  gem list -i pg >/dev/null 2>&1
+}
+
+pg_message () {
+  printf "Unable to install pg gem.\n\n
+  If you are using homebrew, try `brew update` and `brew install
+  postgresql`.\n\n
+  If you are using Ubuntu, try `sudo apt-get install
+  libpq-dev`"
+}
+
 bundle_check () {
   bundle check >/dev/null 2>&1
 }
@@ -136,22 +149,22 @@ bundle_check () {
 verify_postgres_running () {
   echo "Verifying postgres is running..."
   has_postgres || {
-    echo 'Please install postgresql.'
-    exit 1
-  }
+  echo 'Please install postgresql.'
+  exit 1
+}
 
-  postgres_is_running || {
-    echo 'Please ensure postgresql is running'
-    exit 1
+postgres_is_running || {
+echo 'Please ensure postgresql is running'
+exit 1
   }
 }
 
 verify_database_migrations () {
   db_setup || {
-    echo 'Unable to setup the databases for you. Please ensure your
-    database.yml is configured for your system and run `rake db:setup`'
-    exit 1
-  }
+  echo 'Unable to setup the databases for you. Please ensure your
+  database.yml is configured for your system and run `rake db:setup`'
+  exit 1
+}
 }
 
 db_setup () {
