Updating database configuration
* Removing verify_database_configuration - This function copied over the
database configuration, which we already have in
copy_example_config_files. It also runs rake db:create:all, which is
handled in rake db:setup (which we run later), so we don't need this
here. I added the error handling from this to the rake db:setup call and
improved the error message.

* Checking for existence of config files before copying examples over

diff --git a/bin/setup_new b/bin/setup_new
--- a/bin/setup_new
+++ b/bin/setup_new
@@ -135,36 +135,36 @@ exit 1
   }
 }
 
-verify_database_configuration () {
-  if [ ! -f config/database.yml ]
+verify_database_migrations () {
+  bundle exec rake db:abort_if_pending_migrations
+  if [ $? -eq 1 ]
   then
-    cp config/database.travis.yml config/database.yml
-    bundle exec rake db:create:all
-
+    echo 'Creating the database, loading the schema and initializing it with the seed
+    data'
+    bundle exec rake db:setup
     if [ $? -ne 0 ]
     then
-      echo 'Unable to create the databases for you. Please ensure your database.yml is configured for your system and run rake db:create:all'
+      echo 'Unable to setup the databases for you. Please ensure your
+      database.yml is configured for your system and run rake db:setup'
       exit 0
     fi
   fi
 }
 
-verify_database_migrations () {
-  verify_database_configuration
-
-  bundle exec rake db:abort_if_pending_migrations
-  if [ $? -eq 1 ]
-  then
-    echo 'Running migrations...'
-    bundle exec rake db:setup db:test:prepare
-  fi
-}
-
 copy_example_config_files () {
   echo "Copying example config files..."
-  cp config/application.example.yml config/application.yml
-  cp config/smtp.example.yml config/smtp.yml
-  cp config/database.example.yml config/database.yml
+  if [ ! -f config/database.yml ]
+  then
+    cp config/application.example.yml config/application.yml
+  fi
+  if [ ! -f config/smtp.example.yml ]
+  then
+    cp config/smtp.example.yml config/smtp.yml
+  fi
+  if [ ! -f config/database.example.yml ]
+  then
+    cp config/database.example.yml config/database.yml
+  fi
 }
 
 # start it up!!
